
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  build:
    name: "uniauth-gateway"
    arch: "amd64"
    system: "linux"
    path: "./bin"
    exitWhenError: true
    extra: "-ldflags=\"-w -s\""